import type { AppState, Category, ExpenseCategory } from './types'

export const categories: Category[] = [
  'Food & Dishes',
  'Spirits',
  'Wines',
  'Beers & Ciders',
  'Soft Drinks',
  'Cocktail Mixers',
  'Hot Beverages',
  'Dairy & Fresh',
  'Dry Goods',
  'Cleaning & Hygiene',
  'Packaging',
]

export const expenseCategories: ExpenseCategory[] = [
  'Rent',
  'Utilities',
  'Supplies',
  'Payroll',
  'Maintenance',
  'Marketing',
]

export const seedState: AppState = {
  inventory: [
    // ── Food & Dishes ──────────────────────────────────────────
    {
      id: 'house-burger',
      name: 'House Burger',
      category: 'Food & Dishes',
      unit: 'plates',
      location: 'Kitchen Pass',
      supplier: 'Farmhouse Foods',
      sellPrice: 14,
      costPrice: 4.8,
      inStock: 36,
      parLevel: 48,
      dailySold: 26,
      lastDelivery: 'Today, 06:45',
    },
    {
      id: 'loaded-fries',
      name: 'Loaded Fries',
      category: 'Food & Dishes',
      unit: 'plates',
      location: 'Kitchen Pass',
      supplier: 'Farmhouse Foods',
      sellPrice: 9.5,
      costPrice: 2.9,
      inStock: 42,
      parLevel: 40,
      dailySold: 19,
      lastDelivery: 'Today, 06:45',
    },
    {
      id: 'caesar-salad',
      name: 'Caesar Salad',
      category: 'Food & Dishes',
      unit: 'bowls',
      location: 'Prep Station',
      supplier: 'Greens Market',
      sellPrice: 11,
      costPrice: 3.4,
      inStock: 18,
      parLevel: 24,
      dailySold: 12,
      lastDelivery: 'Today, 05:50',
    },
    {
      id: 'chicken-wings',
      name: 'Crispy Chicken Wings',
      category: 'Food & Dishes',
      unit: 'portions',
      location: 'Kitchen Pass',
      supplier: 'Farmhouse Foods',
      sellPrice: 12,
      costPrice: 3.8,
      inStock: 28,
      parLevel: 40,
      dailySold: 22,
      lastDelivery: 'Today, 06:45',
    },
    {
      id: 'nachos',
      name: 'Bar Nachos',
      category: 'Food & Dishes',
      unit: 'portions',
      location: 'Kitchen Pass',
      supplier: 'Farmhouse Foods',
      sellPrice: 8.5,
      costPrice: 2.2,
      inStock: 55,
      parLevel: 40,
      dailySold: 14,
      lastDelivery: 'Yesterday, 07:00',
    },
    // ── Spirits ───────────────────────────────────────────────
    {
      id: 'house-vodka',
      name: 'House Vodka',
      category: 'Spirits',
      unit: 'shots',
      location: 'Back Bar',
      supplier: 'Prime Spirits Ltd.',
      sellPrice: 6.5,
      costPrice: 1.8,
      inStock: 140,
      parLevel: 120,
      dailySold: 42,
      lastDelivery: 'Yesterday, 13:25',
    },
    {
      id: 'london-gin',
      name: 'London Dry Gin',
      category: 'Spirits',
      unit: 'shots',
      location: 'Back Bar',
      supplier: 'Prime Spirits Ltd.',
      sellPrice: 7,
      costPrice: 2.1,
      inStock: 76,
      parLevel: 90,
      dailySold: 28,
      lastDelivery: 'Yesterday, 13:25',
    },
    {
      id: 'aged-whiskey',
      name: 'Aged Whiskey',
      category: 'Spirits',
      unit: 'pours',
      location: 'Reserve Shelf',
      supplier: 'Royal Cask Supply',
      sellPrice: 12,
      costPrice: 3.6,
      inStock: 52,
      parLevel: 60,
      dailySold: 15,
      lastDelivery: '2 days ago',
    },
    {
      id: 'dark-rum',
      name: 'Dark Rum',
      category: 'Spirits',
      unit: 'shots',
      location: 'Back Bar',
      supplier: 'Prime Spirits Ltd.',
      sellPrice: 6.5,
      costPrice: 1.7,
      inStock: 95,
      parLevel: 80,
      dailySold: 18,
      lastDelivery: '2 days ago',
    },
    {
      id: 'silver-tequila',
      name: 'Silver Tequila',
      category: 'Spirits',
      unit: 'shots',
      location: 'Back Bar',
      supplier: 'Prime Spirits Ltd.',
      sellPrice: 7,
      costPrice: 2.0,
      inStock: 60,
      parLevel: 80,
      dailySold: 24,
      lastDelivery: 'Yesterday, 13:25',
    },
    // ── Wines ─────────────────────────────────────────────────
    {
      id: 'house-red',
      name: 'House Red Wine',
      category: 'Wines',
      unit: 'glasses',
      location: 'Wine Rack',
      supplier: 'Vino Select',
      sellPrice: 8,
      costPrice: 2.2,
      inStock: 88,
      parLevel: 96,
      dailySold: 34,
      lastDelivery: 'Yesterday, 10:00',
    },
    {
      id: 'house-white',
      name: 'House White Wine',
      category: 'Wines',
      unit: 'glasses',
      location: 'Wine Rack',
      supplier: 'Vino Select',
      sellPrice: 8,
      costPrice: 2.0,
      inStock: 72,
      parLevel: 96,
      dailySold: 30,
      lastDelivery: 'Yesterday, 10:00',
    },
    {
      id: 'prosecco',
      name: 'Prosecco',
      category: 'Wines',
      unit: 'glasses',
      location: 'Wine Rack',
      supplier: 'Vino Select',
      sellPrice: 10,
      costPrice: 3.0,
      inStock: 48,
      parLevel: 60,
      dailySold: 20,
      lastDelivery: '2 days ago',
    },
    {
      id: 'rose-wine',
      name: 'Rosé Wine',
      category: 'Wines',
      unit: 'glasses',
      location: 'Wine Rack',
      supplier: 'Vino Select',
      sellPrice: 9,
      costPrice: 2.5,
      inStock: 40,
      parLevel: 48,
      dailySold: 16,
      lastDelivery: '2 days ago',
    },
    // ── Beers & Ciders ────────────────────────────────────────
    {
      id: 'lager-draft',
      name: 'Draft Lager (Pint)',
      category: 'Beers & Ciders',
      unit: 'pints',
      location: 'Tap Room',
      supplier: 'Harbor Beverage Co.',
      sellPrice: 5.5,
      costPrice: 1.2,
      inStock: 220,
      parLevel: 240,
      dailySold: 120,
      lastDelivery: 'Today, 08:30',
    },
    {
      id: 'craft-ipa',
      name: 'Craft IPA Bottle',
      category: 'Beers & Ciders',
      unit: 'bottles',
      location: 'Cold Room A',
      supplier: 'Hop & Barrel Co.',
      sellPrice: 6,
      costPrice: 1.9,
      inStock: 84,
      parLevel: 96,
      dailySold: 38,
      lastDelivery: 'Today, 08:30',
    },
    {
      id: 'bottled-cider',
      name: 'Sparkling Cider',
      category: 'Beers & Ciders',
      unit: 'bottles',
      location: 'Cold Room A',
      supplier: 'Harbor Beverage Co.',
      sellPrice: 5,
      costPrice: 1.4,
      inStock: 60,
      parLevel: 72,
      dailySold: 22,
      lastDelivery: 'Today, 08:30',
    },
    {
      id: 'alcohol-free-beer',
      name: 'Alcohol-Free Beer',
      category: 'Beers & Ciders',
      unit: 'bottles',
      location: 'Cold Room B',
      supplier: 'Harbor Beverage Co.',
      sellPrice: 4.5,
      costPrice: 1.1,
      inStock: 36,
      parLevel: 48,
      dailySold: 10,
      lastDelivery: 'Yesterday, 16:10',
    },
    // ── Soft Drinks ───────────────────────────────────────────
    {
      id: 'cola',
      name: 'Cola (330ml)',
      category: 'Soft Drinks',
      unit: 'cans',
      location: 'Cold Room B',
      supplier: 'Metro Refreshments',
      sellPrice: 3,
      costPrice: 0.6,
      inStock: 144,
      parLevel: 120,
      dailySold: 55,
      lastDelivery: 'Yesterday, 16:10',
    },
    {
      id: 'orange-juice',
      name: 'Fresh Orange Juice',
      category: 'Soft Drinks',
      unit: 'glasses',
      location: 'Cold Room B',
      supplier: 'Greens Market',
      sellPrice: 4,
      costPrice: 1.2,
      inStock: 40,
      parLevel: 48,
      dailySold: 22,
      lastDelivery: 'Today, 05:50',
    },
    {
      id: 'sparkling-water',
      name: 'Sparkling Water',
      category: 'Soft Drinks',
      unit: 'bottles',
      location: 'Cold Room B',
      supplier: 'Metro Refreshments',
      sellPrice: 3,
      costPrice: 0.5,
      inStock: 96,
      parLevel: 80,
      dailySold: 30,
      lastDelivery: 'Yesterday, 16:10',
    },
    // ── Cocktail Mixers ───────────────────────────────────────
    {
      id: 'tonic-water',
      name: 'Tonic Water',
      category: 'Cocktail Mixers',
      unit: 'cans',
      location: 'Mixer Station',
      supplier: 'Metro Refreshments',
      sellPrice: 2.5,
      costPrice: 0.6,
      inStock: 84,
      parLevel: 90,
      dailySold: 38,
      lastDelivery: 'Yesterday, 16:10',
    },
    {
      id: 'simple-syrup',
      name: 'Simple Syrup',
      category: 'Cocktail Mixers',
      unit: 'bottles (1L)',
      location: 'Mixer Station',
      supplier: 'Bartender Supply Co.',
      sellPrice: 0,
      costPrice: 3.2,
      inStock: 8,
      parLevel: 12,
      dailySold: 0,
      lastDelivery: '3 days ago',
    },
    {
      id: 'grenadine',
      name: 'Grenadine Syrup',
      category: 'Cocktail Mixers',
      unit: 'bottles',
      location: 'Mixer Station',
      supplier: 'Bartender Supply Co.',
      sellPrice: 0,
      costPrice: 4.5,
      inStock: 6,
      parLevel: 8,
      dailySold: 0,
      lastDelivery: '4 days ago',
    },
    // ── Hot Beverages ─────────────────────────────────────────
    {
      id: 'espresso',
      name: 'Espresso Shot',
      category: 'Hot Beverages',
      unit: 'cups',
      location: 'Coffee Station',
      supplier: 'Café Origin Roasters',
      sellPrice: 3,
      costPrice: 0.45,
      inStock: 200,
      parLevel: 150,
      dailySold: 65,
      lastDelivery: '2 days ago',
    },
    {
      id: 'flat-white',
      name: 'Flat White',
      category: 'Hot Beverages',
      unit: 'cups',
      location: 'Coffee Station',
      supplier: 'Café Origin Roasters',
      sellPrice: 4.5,
      costPrice: 0.85,
      inStock: 150,
      parLevel: 100,
      dailySold: 40,
      lastDelivery: '2 days ago',
    },
    {
      id: 'earl-grey',
      name: 'Earl Grey Tea',
      category: 'Hot Beverages',
      unit: 'cups',
      location: 'Coffee Station',
      supplier: 'Tea Traders Ltd.',
      sellPrice: 3.5,
      costPrice: 0.3,
      inStock: 80,
      parLevel: 60,
      dailySold: 18,
      lastDelivery: '4 days ago',
    },
    // ── Dairy & Fresh ─────────────────────────────────────────
    {
      id: 'full-fat-milk',
      name: 'Full Fat Milk (2L)',
      category: 'Dairy & Fresh',
      unit: 'cartons',
      location: 'Cold Store',
      supplier: 'Greens Market',
      sellPrice: 0,
      costPrice: 1.8,
      inStock: 12,
      parLevel: 18,
      dailySold: 0,
      lastDelivery: 'Today, 05:50',
    },
    {
      id: 'double-cream',
      name: 'Double Cream (500ml)',
      category: 'Dairy & Fresh',
      unit: 'cartons',
      location: 'Cold Store',
      supplier: 'Greens Market',
      sellPrice: 0,
      costPrice: 2.4,
      inStock: 6,
      parLevel: 10,
      dailySold: 0,
      lastDelivery: 'Today, 05:50',
    },
    {
      id: 'plant-milk',
      name: 'Oat Milk (1L)',
      category: 'Dairy & Fresh',
      unit: 'cartons',
      location: 'Cold Store',
      supplier: 'Greens Market',
      sellPrice: 0,
      costPrice: 2.1,
      inStock: 8,
      parLevel: 12,
      dailySold: 0,
      lastDelivery: 'Today, 05:50',
    },
    // ── Dry Goods ─────────────────────────────────────────────
    {
      id: 'burger-buns',
      name: 'Brioche Buns (pack)',
      category: 'Dry Goods',
      unit: 'packs',
      location: 'Dry Store',
      supplier: 'Farmhouse Foods',
      sellPrice: 0,
      costPrice: 3.5,
      inStock: 22,
      parLevel: 30,
      dailySold: 0,
      lastDelivery: 'Today, 06:45',
    },
    {
      id: 'table-salt',
      name: 'Sea Salt (1kg)',
      category: 'Dry Goods',
      unit: 'bags',
      location: 'Dry Store',
      supplier: 'Premier Wholesale',
      sellPrice: 0,
      costPrice: 1.2,
      inStock: 5,
      parLevel: 8,
      dailySold: 0,
      lastDelivery: '5 days ago',
    },
    {
      id: 'cooking-oil',
      name: 'Vegetable Oil (5L)',
      category: 'Dry Goods',
      unit: 'bottles',
      location: 'Dry Store',
      supplier: 'Premier Wholesale',
      sellPrice: 0,
      costPrice: 7.5,
      inStock: 4,
      parLevel: 6,
      dailySold: 0,
      lastDelivery: '3 days ago',
    },
    // ── Cleaning & Hygiene ────────────────────────────────────
    {
      id: 'glass-cleaner',
      name: 'Bar Glass Sanitizer (5L)',
      category: 'Cleaning & Hygiene',
      unit: 'containers',
      location: 'Service Area',
      supplier: 'CleanPro Supplies',
      sellPrice: 0,
      costPrice: 12,
      inStock: 3,
      parLevel: 5,
      dailySold: 0,
      lastDelivery: '6 days ago',
    },
    {
      id: 'floor-cleaner',
      name: 'Floor Disinfectant (5L)',
      category: 'Cleaning & Hygiene',
      unit: 'containers',
      location: 'Storage Room',
      supplier: 'CleanPro Supplies',
      sellPrice: 0,
      costPrice: 9.5,
      inStock: 2,
      parLevel: 4,
      dailySold: 0,
      lastDelivery: '6 days ago',
    },
    {
      id: 'hand-sanitizer',
      name: 'Hand Sanitizer (1L)',
      category: 'Cleaning & Hygiene',
      unit: 'bottles',
      location: 'Service Area',
      supplier: 'CleanPro Supplies',
      sellPrice: 0,
      costPrice: 5.5,
      inStock: 6,
      parLevel: 8,
      dailySold: 0,
      lastDelivery: '3 days ago',
    },
    // ── Packaging ─────────────────────────────────────────────
    {
      id: 'takeaway-boxes',
      name: 'Takeaway Boxes (x50)',
      category: 'Packaging',
      unit: 'packs',
      location: 'Storage Room',
      supplier: 'PackRight Ltd.',
      sellPrice: 0,
      costPrice: 8,
      inStock: 10,
      parLevel: 15,
      dailySold: 0,
      lastDelivery: '4 days ago',
    },
    {
      id: 'paper-cups',
      name: 'Hot Paper Cups (x100)',
      category: 'Packaging',
      unit: 'packs',
      location: 'Coffee Station',
      supplier: 'PackRight Ltd.',
      sellPrice: 0,
      costPrice: 6.5,
      inStock: 7,
      parLevel: 10,
      dailySold: 0,
      lastDelivery: '4 days ago',
    },
    {
      id: 'paper-straws',
      name: 'Paper Straws (x200)',
      category: 'Packaging',
      unit: 'packs',
      location: 'Bar Counter',
      supplier: 'PackRight Ltd.',
      sellPrice: 0,
      costPrice: 4,
      inStock: 5,
      parLevel: 8,
      dailySold: 0,
      lastDelivery: '5 days ago',
    },
  ],
  deliveries: [
    {
      id: 'delivery-1',
      supplier: 'Harbor Beverage Co.',
      eta: 'Today, 18:00',
      itemId: 'lager-draft',
      itemName: 'Draft Lager (Pint)',
      quantity: 240,
      unitCost: 1.05,
      status: 'En Route',
    },
    {
      id: 'delivery-2',
      supplier: 'Greens Market',
      eta: 'Tomorrow, 08:00',
      itemId: 'caesar-salad',
      itemName: 'Caesar Salad',
      quantity: 32,
      unitCost: 3.1,
      status: 'Scheduled',
    },
    {
      id: 'delivery-3',
      supplier: 'Prime Spirits Ltd.',
      eta: 'Tomorrow, 15:30',
      itemId: 'london-gin',
      itemName: 'London Dry Gin',
      quantity: 48,
      unitCost: 1.95,
      status: 'Scheduled',
    },
    {
      id: 'delivery-4',
      supplier: 'CleanPro Supplies',
      eta: 'Tomorrow, 10:00',
      itemId: 'glass-cleaner',
      itemName: 'Bar Glass Sanitizer (5L)',
      quantity: 6,
      unitCost: 11.5,
      status: 'Scheduled',
    },
  ],
  expenses: [
    {
      id: 'expense-1',
      name: 'Daily rent allocation',
      category: 'Rent',
      amount: 180,
      dueLabel: 'Today',
      recurring: true,
    },
    {
      id: 'expense-2',
      name: 'Utilities and cooling',
      category: 'Utilities',
      amount: 64,
      dueLabel: 'Today',
      recurring: true,
    },
    {
      id: 'expense-3',
      name: 'Cleaning supplies restock',
      category: 'Supplies',
      amount: 28,
      dueLabel: 'Today',
      recurring: false,
    },
    {
      id: 'expense-4',
      name: 'Live music license',
      category: 'Marketing',
      amount: 55,
      dueLabel: 'This week',
      recurring: false,
    },
    {
      id: 'expense-5',
      name: 'Staff wages (part-time)',
      category: 'Payroll',
      amount: 320,
      dueLabel: 'This week',
      recurring: true,
    },
    {
      id: 'expense-6',
      name: 'Refrigeration service',
      category: 'Maintenance',
      amount: 95,
      dueLabel: 'This week',
      recurring: false,
    },
  ],
  weeklyData: [
    { day: 'Mon', revenue: 1420, costs: 620 },
    { day: 'Tue', revenue: 1680, costs: 590 },
    { day: 'Wed', revenue: 1510, costs: 640 },
    { day: 'Thu', revenue: 1963, costs: 742 },
    { day: 'Fri', revenue: 2780, costs: 860 },
    { day: 'Sat', revenue: 3140, costs: 940 },
    { day: 'Sun', revenue: 2460, costs: 780 },
  ],
}